#ifndef CONFIG_H
#define CONFIG_H


#define TINYBLAS_ENABLE_SSE
#define TINYBLAS_ENABLE_AVX
#define TINYBLAS_ENABLE_PARALLELIZE

//#define TINYBLAS_DEFAULT_TO_ROW_MAJOR
#define TINYBLAS_DEFAULT_TO_COL_MAJOR   //default




#endif // CONFIG_H
